spring:
  application:
    name: securityservice
    
server:
   port: 8069
   context-path: /api

security:
  user:
    name: user
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
      access-token-uri: http://localhost:8069/api/oauth/token
      user-authorization-uri: http://localhost:8069/api/oauth/authorize

eureka:
  instance:
    appname: securityservice
    leaseRenewalIntervalInSeconds: 10 #default 30 seconds
    metadataMap:
      instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
      #${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

